# Generated by Django 5.0.6 on 2024-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0004_alter_agendamentos_agendado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalasReservadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=50)),
            ],
        ),
    ]
